baseURL = 'https://h-tomo-tohoku.github.io/'
languageCode = 'en-us'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'Tomomasa Hara'

theme = "hugo-theme-techdoc"
